name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - plyfile=0.8.1
  - python=3.11
  - pip=25.0.1
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tqdm
  - hdbscan
  - matplotlib
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization_contrastive_f
    - submodules/diff-gaussian-rasterization-depth
    - third_party/segment-anything
    - dearpygui
    - opencv-python
    - open-clip-torch
    - joblib==1.1.0