name: saga
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
  - rapidsai
dependencies:
  - cuda-toolkit=12.4
  - plyfile
  - python=3.11
  - pip=25.0
  - tqdm
  - hdbscan
  - matplotlib
  - rapids==25.02
  - cuda-cudart
  - cuda-version=12 
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch
    - torchvision
    - torchaudio
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization_contrastive_f
    - submodules/diff-gaussian-rasterization-depth
    - third_party/segment-anything
    - dearpygui
    - opencv-python
    - open-clip-torch
    - jupyter
    - git+https://github.com/facebookresearch/pytorch3d.git@stable
    - joblib==1.1.0
    - numpy==2.0
variables:
  CUDA_HOME: ${CONDA_PREFIX}
  LD_LIBRARY_PATH: ${CONDA_PREFIX}/targets/x86_64-linux/include/lib
  CPATH: ${CONDA_PREFIX}/targets/x86_64-linux/include